const en = {
  Profile: "Profile",
  header: "Language",
  language: "Select a Language",
  EditProfile: "EditProfile",
  Notification: "Notification ",
  Payment: "Payment",
  Privacy: "Privacy",
  Male: "Male",
  Female: "Female",
  Others: "Others",

  Appointment: "Appointment",
  "Enter Your Name": "Enter Your Name",
  "Enter Your Email": "Enter Your Email",
  Update: "Update",
  "Privacy Policy": "Privacy Policy",
  "Types of Data We Collect": "Types of Data We Collect",
  "Disclouser of your Personal Data": "Disclouser of your Personal Data",
  "Use of Your Personal Data": " Use of Your Personal Data",
  Sound: "Sound",
  Vibrate: "Vibrate",
  "Special Offers": "Special Offers",
  "Promo & Discount": "Promo & Discount",
  "New Service Available": "New Service Available",
};

const sp = {
    Profile:"Perfil",
    header:"idioma",
    language: "Selecciona un idioma",
   "EditProfile":"Edit arperfil",
    Notification:" Notificación",
    Payment:"Pago",
    Privacy:" Privacidad",
    Male:"Masculina",
    Female:"Femenina",
    Others:" otras(feminine)",
     Appointemnt:"cita",
    "Enter Your Name" :"Introduzca su nombre",
    "Enter Your Email": "escribe tu correo electronico",
    Update:"Actualizar",
    "Privacy Policy":"Política de privacidad",
    "Types of Data We Collect":"Tipos de datos que recopilamos",
    "Disclouser of your Personal Data":"Divulgador de sus Datos Personales",
    "Use of Your Personal Data":"Uso de sus datos personales",
    Sound:"Sonido",
    Vibrate: "Vibrar",
    "Special Offers":"Oferta especial",
    "Promo & Discount": "Promoción y descuento",
    "New Service Available":"Nuevo servicio disponible",


};

const bn = {
  Profile: "প্রোফাইল",
  header: "ভাষা",
  language: "একটি ভাষা নির্বাচন করুন",
  EditProfile: "জীবন বৃত্তান্ত সম্পাদনা",
  Notification: "বিজ্ঞপ্তি",
  Payment: "পেমেন্ট",
  Privacy: " গোপনীয়তা",
  Male: "পুরুষ",
  Female: "মহিলা",
  Others: " অন্যান্য",
  Appointment: "অ্যাপয়েন্টমেন্ট",
  "Enter Your Name": "আপনার নাম লিখ",
  "Enter Your Email": "আপনার ইমেইল লিখুন",
  Update: "আপ টু ডেট",
  "Privacy Policy": "গোপনীয়তা নীতি",
  "Types of Data We Collect": "আমরা যে ধরনের ডাটা সংগ্রহ করি",
  "Disclouser of your Personal Data": " আপনার ব্যক্তিগত তথ্য প্রকাশক",
  "Use of Your Personal Data": " আপনার ব্যক্তিগত ডেটার ব্যবহার",
  Sound: "শব্দ",
  Vibrate: "কম্পন",
  "Special Offers": "স্পেশাল অফার",
  "Promo & Discount": "প্রচার এবং ডিসকাউন্ট",
  "New Service Available": "নতুন পরিষেবা উপলব্ধ",
};
export { en, sp, bn };